iweb_client/urls.py
from django.contrib import admin
from django.urls import include, path
from iweb_client import views

urlpatterns = [
    path('', views.homepage, name="homepage"),
    path('parkings/', include('parkings.urls')),
    path('admin/', admin.site.urls),
]

parkings/urls.py
# to start app: python manage.py startapp polls
from django.urls import path
from . import views

app_name = 'parkings'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:idParking>/', views.details, name='details'),
    path('login/<user_id>', views.startLogin, name='startLogin'),
    path('user/info', views.userInfo, name='userInfo'),
    path('logOut', views.logOut, name='logOut'),
]

parkings/models.py
from django.db import models

# Create your models here.

iweb_client/views.py
import requests
from django.shortcuts import render


def homepage(request):
    return render(request, 'parking/mainView.html')

parkings/views.py
import json

import requests
from django.shortcuts import render, redirect

weatherURL = 'https://api.openweathermap.org/data/2.5/weather?id=2514256&appid=a616b07331d06ea639f3b99c87ef5830&units=metric&lang=es'
apiURL = 'https://ingenieriaweb-260616.appspot.com/api/v1/'
current_user_id = '116640585785426680346'


def index(request):
    try:
        weatherResponse = requests.get(weatherURL)
        weatherData = weatherResponse.json()

        userResponse = requests.get(apiURL + 'users/byUserId/' + current_user_id)
        userData = userResponse.json()

        parkingsResponse = requests.get(apiURL + 'openData/parkings')
        parkingsData = parkingsResponse.json()

        locationsResponse = requests.get(apiURL + 'openData/locations')
        locationsData = json.dumps(locationsResponse.json()['features'])
        i = 1
        availableSpots = 0
        totalSpots = 0
        parkingList = []

        for item in parkingsData:
            aux = ''
            info = item['availableSpotNumber']['value']

            if info == str(-1) or info is None:
                aux = 'N/A'
            else:
                aux = info
                availableSpots += int(info)
                totalSpots += int(item['totalSpotNumber']['value'])

            parkingList.append({'id': i,
                                'parking': item['name']['value'],
                                'available': aux,
                                'address': item['description']['value'],
                                })
            i += 1

        context = {
                   'weather': weatherData['weather'][0]['description'],
                   'temperature': str(weatherData['main']['temp']) + 'ºC',
                   'humidity': str(weatherData['main']['humidity']) + '%',
                   'user_name': userData[0]['full_name'],
                   'parkingList': parkingList,
                   'counter': i - 1,
                   'totalSpots': totalSpots,
                   'availableSpots': availableSpots,
                   'locationsData': locationsData,
                   }

        return render(request, 'parking/parkingsPage.html', context)

    except Exception as e:
        print('not valid username')
        raise e


def details(request, idParking):
    try:
        weatherResponse = requests.get(weatherURL)
        weatherData = weatherResponse.json()

        userResponse = requests.get(apiURL + 'users/byUserId/' + current_user_id)
        userData = userResponse.json()

        reportResponse = requests.get(apiURL + 'reports/byParking/' + str(idParking))
        reportData = reportResponse.json()

        parkingResponse = requests.get(apiURL + 'openData/parking/' + str(idParking))
        parkingData = parkingResponse.json()

        locationResponse = requests.get(apiURL + 'openData/location/' + str(idParking))
        locationData = locationResponse.json()

        reportList = []
        for item in reportData:
            userSearchResponse = requests.get(apiURL + 'users/byUserId/' + item['user_id'])
            userSearchData = userSearchResponse.json()
            it = {'user_id': userSearchData[0]['full_name'],
                  'user_text': item['text']}
            reportList.append(it)

        context = {
            'weather': weatherData['weather'][0]['description'],
            'temperature': str(weatherData['main']['temp']) + 'ºC',
            'humidity': str(weatherData['main']['humidity']) + '%',
            'user_name': userData[0]['full_name'],
            'id': idParking,
            'name': parkingData['name']['value'],
            'requiredPermit': parkingData['requiredPermit']['value'],
            'allowedVehicleType': parkingData['allowedVehicleType']['value'],
            'availableSpotNumber': parkingData['availableSpotNumber']['value'],
            'totalSpotNumber': parkingData['totalSpotNumber']['value'],
            'description': parkingData['description']['value'],
            'longitude': locationData['geometry']['coordinates'][0],
            'latitude': locationData['geometry']['coordinates'][1],
            'reportList': reportList,
        }
        return render(request, 'parking/parkingDetails.html', context)

    except Exception as e:
        print('not valid username')
        raise e


def startLogin(request, user_id):

    global current_user_id
    valid_user = False

    try:
        userResponse = requests.get(apiURL + 'users/byUserId/' + user_id)
        userData = userResponse.json()

        current_user_id = userData[0]['user_id']
        valid_user = current_user_id != ''

    except Exception as e:
        print('not valid login ID')
        raise e

    if(valid_user):
        return redirect('https://iwebclient-host-16.herokuapp.com/parkings')
    else:
        return redirect('https://iwebclient-host-16.herokuapp.com')


def userInfo(request):
    try:
        userResponse = requests.get(apiURL + 'users/byUserId/' + current_user_id)
        userData = userResponse.json()

        context = {
            'user_id': userData[0]['user_id'],
            'user_name': userData[0]['full_name'],
        }

        return render(request, 'parking/userInfo.html', context)

    except Exception as e:
        print('not valid username')
        raise e


def logOut(request):
    global current_user_id
    current_user_id = ''
    return render(request, 'parking/mainView.html')

templates/parking/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>
  .container-fluid {
    padding: 60px 50px;
  }
  @media screen and (max-width: 768px) {
    .col-sm-4 {
      text-align: center;
      margin: 25px 0;
    }
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  .bg-4 {
    background-color: #2f2f2f; /* Black Gray */
    color: #fff;
  }
  .container-fluid {
    padding-top: 40px;
    padding-bottom: 40px;
  }
    .my-custom-scrollbar {
    position: relative;
    height: 400px;
    overflow: auto;
    }
    .table-wrapper-scroll-y {
    display: block;
    }

  .navbar {
    padding-top: 15px;
    padding-bottom: 15px;
    border: 0;
    border-radius: 0;
    margin-bottom: 0;
    font-size: 12px;
    letter-spacing: 2px;
  }

  .lot-of-info-div{
      height: 100%;
      max-height: 100px;
      overflow-y: scroll;
  }

    .table-row{
     cursor:pointer;
    }
  p {font-size: 16px;}
   #myInput {
    padding: 20px;
    margin-top: -6px;
    border: 0;
    border-radius: 0;
    background: #f1f1f1;
  }
  </style>

  <script>
      $(document).ready(function($) {
        $(".table-row").click(function() {
            window.document.location = $(this).data("href");
        });
      });

  </script>

  <script>
      $(document).ready(function($) {
        $(".table-row").click(function() {
            window.document.location = $(this).data("href");
        });
      });

  </script>
    {% block header %}
    {% endblock %}
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PARKAROUND</a>
            </div>
            <div class="container">
                <div class="navbar-nav navbar-right" style="padding-top: 15px">
                    <span class="glyphicon glyphicon-cloud"></span> {{ weather }}
                    <span class="glyphicon glyphicon-certificate"></span> {{ temperature }}
                    <span class="glyphicon glyphicon-tint"></span> {{ humidity }}
                    <span class=""></span> |
                    <span class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">{{ user_name }}
                        <span class="glyphicon glyphicon-user profile"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href={% url 'parkings:userInfo' %}>Edit</a></li>
                        <li role="presentation" class="divider"></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="{% url 'parkings:logOut' %}">Sign out</a></li>
                    </ul>
                </span>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <!-- Footer -->
    <footer class="container-fluid bg-4 text-center">
      <p>Bootstrap Theme iWeb project</p>
    </footer>
</body>
</html>

templates/parking/mainView.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Theme Made By www.w3schools.com - No Copyright -->
  <title>Parkings Malaga</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <style>

  p {font-size: 16px;}
  .margin {margin-bottom: 45px;}
  .bg-2 {
    background-color: #474e5d; /* Dark Blue */
    color: #ffffff;
  }
  .bg-4 {
    background-color: #2f2f2f; /* Black Gray */
    color: #fff;
  }
  .logo{
      font-size: 200px;
  }

  .container-fluid {
    padding-top: 70px;
    padding-bottom: 70px;
  }
  .navbar {
    padding-top: 15px;
    padding-bottom: 15px;
    border: 0;
    border-radius: 0;
    margin-bottom: 0;
    font-size: 12px;
    letter-spacing: 5px;
  }
  </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PARKAROUND</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="https://ingenieriaweb-260616.appspot.com/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>

<!-- First   Container -->
<div class="container-fluid text-center">
  <h3 class="margin">What can I do?</h3>
  <p>Search for parkings, check live data and directions to find them. </p>

  <div class="row">
    <span class="glyphicon glyphicon-globe logo"></span>
  </div>
</div>

<!-- Footer -->
<footer class="container-fluid bg-4 text-center">
  <p>Bootstrap Theme iWeb project</p>
</footer>

</body>
</html>

templates/parking/parkingDetails.html
{% extends 'parking/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% block header %}
        <meta charset="UTF-8">
        <title>Detalles</title>

        <style type="text/css">
            .info > h4 { display: inline-block; }
            .info span { margin-left: 0; }
        </style>
        <script type="text/javascript">
        function myMap() {
            //we initialize the map
            let mapProp = {
                center: new google.maps.LatLng(36.719101, -4.420083),
                zoomControl: true,
                mapTypeControl: false,
                scaleControl: false,
                streetViewControl: false,
                rotateControl: false,
                fullscreenControl: false,
                zoom: 14,
            };
            let map = new google.maps.Map(document.getElementById("googleMap"), mapProp);

            //we locate the user
            navigator.geolocation.getCurrentPosition(
                function getLatLon(position){
                    let latitude = position.coords.latitude;
                    let longitude = position.coords.longitude;

                    let userLocation = {
                       'lat': latitude,
                       'lng': longitude,
                     };

                    let parking = {
                        lat: {{ latitude }},
                        lng: {{ longitude }},
                    };


                    //routing to the parking
                    let directionsService = new google.maps.DirectionsService();
                    let directionsRequest = {
                        origin: userLocation,
                        destination: parking,
                        travelMode: google.maps.DirectionsTravelMode.DRIVING,
                        unitSystem: google.maps.UnitSystem.Metric
                    };


                    directionsService.route(
                        directionsRequest, function(response, status){
                            if(status === google.maps.DirectionsStatus.OK){
                                new google.maps.DirectionsRenderer({
                                    map: map,
                                    directions: response
                                });
                                changeScript(userLocation.lat, userLocation.lng, parking.lat, parking.lng);
                            }else{
                                $("#error").append("Unable to retrieve your route<br />");
                            }
                        }
                    );

                }, function error(msg){
                    alert('Geolocation is not enabled');

                }, {timeout: 10000, enableHighAccuracy: true});
        }
         function changeScript(originLat, originLng, destinationLat, destinationLng) {
            document.getElementById("apikey").src = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBmSgcdFBstr0iulZUzGm8AfTnIjVGSFEQ&origin=" + originLat + "," + originLng +
                                                    "&destination=" + destinationLat + "," + destinationLng + "&callback=myMap";
        }
    </script>

    <script id="apikey" async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmSgcdFBstr0iulZUzGm8AfTnIjVGSFEQ&callback=myMap">
    </script>

    {% endblock %}
</head>
<body>
    {% block content %}
    <div class="container-fluid text-center justify-content-center">
        <div class="row">
            <div class="col-sm-2"><!-- this div is used for alignment purposes --></div>
            <div class="col-sm-5">
                    <div class="panel panel-default">
                        <div class="panel-body embed-responsive embed-responsive-4by3">
                            <div id="map-container" class="embed-responsive-item">
                                <div id="googleMap" style="width:100%;height:100%;"></div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="col-sm-3 text-left">
                <ul>
                <li>
                    <div class="info">
                        <h4>Id: </h4>
                        <span>{{ id }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Nombre: </h4>
                        <span>{{ name }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Permiso: </h4>
                        <span>{{ requiredPermit }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Tipo de veh&iacute;culo: </h4>
                        <span>{{ allowedVehicleType }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Plazas disponibles: </h4>
                        <span>{{ availableSpotNumber }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Plazas totales: </h4>
                        <span>{{ totalSpotNumber }}</span>
                    </div>
                </li>
                <li>
                    <div class="info">
                        <h4>Descripci&oacute;n: </h4>
                        <span>{{ description }}</span>
                    </div>
                </li>
                </ul>
                <div class="lot-of-info-div">
                {% for item in reportList %}
                    {% for key, value in item.items %}
                        <div class="card">
                            {% if key == 'user_id'%}
                                <div class="card-header">
                                    {{ value }}
                                </div>
                            {% endif %}
                            {% if key == 'user_text' %}
                                <div class="card-body">
                                    <p class="card-text">
                                        {{ value }}
                                    </p>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endfor %}
                </div>
            </div>
        </div>
        <div class="row offset-md-2"><a class="btn btn-default" href="/parkings/">volver</a></div>
    </div>

    {% endblock %}
</body>
</html>

templates/parking/parkingsPage.html
{% extends 'parking/base.html' %}

{% block header %}
    <title>MainMapView</title>

    <script type="text/javascript">
        // We create and initialize the map
        function myMap() {
            let mapProp = {
                center: new google.maps.LatLng(36.719101, -4.420083),
                zoomControl: true,
                mapTypeControl: false,
                scaleControl: false,
                streetViewControl: false,
                rotateControl: false,
                fullscreenControl: false,
                zoom: 14,
            };
            window.map = new google.maps.Map(document.getElementById("googleMap"), mapProp);
            //let map to do it local


            // We geolocate the user
            navigator.geolocation.getCurrentPosition(
                function getLatLon(position){
                    let latitude = position.coords.latitude;
                    let longitude = position.coords.longitude;

                    //here we'll move the map to the user location
                    map.panTo(new google.maps.LatLng(latitude, longitude));

                    let userLocation = {
                        'lat': latitude,
                        'lng': longitude,
                    };

                    // after locating the user we can put a marker on his position
                    let userMark = new google.maps.Marker({
                        position: userLocation,
                        map: map,
                        title: 'you are here',
                    });
                    userMark.setMap(map);

                }, function error(msg){
                    alert('Geolocation is not enabled');

                }, {timeout: 10000, enableHighAccuracy: true});


            // we finally can add a marker for each parking
            let locationsData = {{ locationsData|safe }};

            for(let i = 0; i < Object.keys(locationsData).length; i++){
                if(locationsData[i].geometry.coordinates[1] !== 0){
                    let parking =  {lat:locationsData[i].geometry.coordinates[1],
                                    lng:locationsData[i].geometry.coordinates[0]};
                    let marker = new google.maps.Marker({
                        position: parking,
                        map: map,
                        title: locationsData[i].properties.name});
                    marker.setMap(map);
                }
            }
        }
    </script>

    <script id="apikey" async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBmSgcdFBstr0iulZUzGm8AfTnIjVGSFEQ&callback=myMap">
    </script>
{% endblock %}


{% block content %}

    <!-- 1st container -->

    <div class="container-fluid text-center">
        <div class="row">

            <div class="col-sm-5">
                <div class="panel panel-default">
                    <div class="panel-body embed-responsive embed-responsive-4by3">
                        <div id="map-container" class="embed-responsive-item">
                            <div id="googleMap" style="width:100%;height:100%;"></div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-7">
                <div class="row">
                    <div class="col-sm-1">
                        <form class="form-inline">
                            <div class="dropdown">
                                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                                    Filter
                                    <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    <li><a role="menuitem">ID</a></li>
                                    <li><a role="menuitem">name</a></li>
                                </ul>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-4">
                        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
                    </div>
                </div>

                <div class="table-wrapper-scroll-y my-custom-scrollbar">
                    <table class="table table-borderless-responsive table-hover">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Parking</th>
                            <th scope="col">Free Spots</th>
                            <th scope="col">Address</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in parkingList %}
                            <tr class="table-row" data-href="{% url 'parkings:details' idParking=item.id %}">
                                {% for key, value in item.items %}
                                    {% if key == 'id' %}
                                        <th scope="row">{{ value }}</th>
                                    {% endif %}
                                    {% if key != 'id' %}
                                        <td>{{ value }}</td>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <!-- 2nd Container-->

    <div class="container-fluid text-center">
        <div class="row">
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-home"></span>
                <h4>Registered Parkings</h4>
                <p>{{ counter }}</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-lock"></span>
                <h4>Available Spots</h4>
                <p>{{ availableSpots }}</p>
            </div>
            <div class="col-sm-4">
                <span class="glyphicon glyphicon-lock"></span>
                <h4>Total spots</h4>
                <p>{{ totalSpots }}</p>
            </div>
        </div>
        <br><br>

    </div>

{% endblock %}

templates/parking/userInfo.html
{% extends 'parking/base.html' %}

{% block header %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>UserInfo</title>
{% endblock %}

{% block content %}
    <div class="text-center">
        <i class="fa fa-user fa-5x"></i>
        <ul>
            <li><strong>Id: </strong>{{user_id}}</li>
            <li><strong>Nombre: </strong>{{user_name}}</li>
        </ul>

        <div class="row offset-md-2"><a class="btn btn-default" href="/parkings/">volver</a></div>
    </div>
{% endblock %}